---
apiVersion: hub.traefik.io/v1alpha1
kind: APIGateway
metadata:
  name: travel-gateway
  labels:
    area: crm
spec:
  apiAccesses:
    - crm-all
    - crm-internal
    - admins
    - custom-pick
    - travel-agents